'use client';
import {useEffect,useState} from 'react';
import {ChevronsLeft,ChevronsRight,Maximize2,Minimize2,Database} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {useSidebar} from '@/components/ui/sidebar';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {BASE_METADATA,num} from '@/lib/mock-data';
import {toast} from 'sonner';
export function MenuToggle({inSidebar=false}:{inSidebar?:boolean}){const{open,isMobile,openMobile,toggleSidebar}=useSidebar();const expanded=isMobile?openMobile:open;const label=expanded?'Recolher menu':'Abrir menu';const Icon=expanded?ChevronsLeft:ChevronsRight;return <Button variant="ghost" size="icon" onClick={toggleSidebar} aria-label={label} aria-expanded={expanded} title={label+' (Ctrl/⌘ + B)'} className={inSidebar?'collapse-menu':''}><Icon size={20} aria-hidden="true"/></Button>}
export function FullscreenButton(){const[full,setFull]=useState(false),[supported,setSupported]=useState(true);useEffect(()=>{setSupported(!!document.fullscreenEnabled);const sync=()=>setFull(!!document.fullscreenElement);document.addEventListener('fullscreenchange',sync);return()=>document.removeEventListener('fullscreenchange',sync)},[]);return <Button variant="ghost" size="sm" className="fullscreen-control" title={!supported?'Tela cheia indisponível neste navegador':full?'Sair da tela cheia (Esc)':'Expandir painel em tela cheia'} aria-label={full?'Sair da tela cheia':'Abrir em tela cheia'} aria-pressed={full} disabled={!supported} onClick={async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{toast.info('Este navegador não permitiu abrir a tela cheia.')}}}>{full?<Minimize2 size={17}/>:<Maximize2 size={17}/>}<span>{full?'Sair da tela cheia':'Tela cheia'}</span></Button>}
export function BaseInfo(){const[open,setOpen]=useState(false);const d=(x:string)=>x.split('-').reverse().join('/');return <><Button size="sm" variant="ghost" className="base-info-trigger" onClick={()=>setOpen(true)}><Database size={14}/>Atualização das bases</Button><Sheet open={open} onOpenChange={setOpen}><SheetContent className="overflow-y-auto sm:max-w-lg"><SheetHeader><SheetTitle>Atualização das bases</SheetTitle><SheetDescription>Referência temporal e volume dos dados utilizados na apresentação.</SheetDescription></SheetHeader><div className="base-info-content"><h3>Base consolidada</h3><dl>{[['Emplacamentos',`até ${d(BASE_METADATA.market.to)}`],['Visitas',`até ${d(BASE_METADATA.visits.to)}`],['Oportunidades',`criadas até ${d(BASE_METADATA.opps.to)}`],['Clientes CRM',`${num(BASE_METADATA.crm)} cadastros`],['Estabelecimentos',`${num(BASE_METADATA.establishments)} registros`]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p>Emplacamentos no banco: {d(BASE_METADATA.market.from)} a {d(BASE_METADATA.market.to)}</p><p>Visitas no banco: {d(BASE_METADATA.visits.from)} a {d(BASE_METADATA.visits.to)}</p><p>Oportunidades no banco: {d(BASE_METADATA.opps.from)} a {d(BASE_METADATA.opps.to)}</p></div></SheetContent></Sheet></>}
