import {type Model,num} from './mock-data';
export type DemoRole='manager'|'director';
export function directorInsight(page:string,m:Model){const t=m.total;const pct=(a:number,b:number)=>num(m.percent(a,b))+'%';const top=m.clientRows.slice(0,10).reduce((s,r)=>s+Number(r[5]),0);const branch=[...m.byBranch].sort((a,b)=>b.notVisitedActive-a.notVisitedActive)[0];let findings:{title:string;fact:string;action:string}[];
if(page==='Funil de Vendas')findings=[{title:'Potencial aberto',fact:`${num(t.trucks)} caminhões em ${num(t.open)} oportunidades abertas.`,action:'Conferir os clientes de cada estágio com os responsáveis; volumes não representam conversão prevista.'}];
else if(page==='Qualidade do CRM')findings=[{title:'Contato cadastrado',fact:`${num(t.portfolio-t.contact)} clientes sem contato principal disponível, entre ${num(t.portfolio)} clientes da carteira.`,action:'Usar a lista de pendências para conferir os cadastros antes de orientar uma ação comercial.'}];
else if(page==='Clientes (Emplacamentos)'||page==='Mercado')findings=[{title:'Concentração de compras',fact:`Os dez maiores clientes reúnem ${pct(top,t.market)} dos ${num(t.market)} emplacamentos no recorte.`,action:'Conferir a composição dos compradores antes de interpretar concentração como dependência comercial.'}];
else if(page==='Trações')findings=[{title:'Participação no segmento',fact:`${num(t.daf)} emplacamentos DAF entre ${num(t.market)} veículos: ${pct(t.daf,t.market)} do segmento filtrado.`,action:'Comparar o share e o volume de cada configuração nas duas visualizações acima.'}];
else findings=[{title:'Cobertura da carteira',fact:`${num(t.visited)} de ${num(t.portfolio)} clientes receberam visita no período: ${pct(t.visited,t.portfolio)}.`,action:'Conferir clientes ativos sem visita antes de redistribuir a agenda.'},{title:'Distribuição de pendências',fact:branch?`${branch.name} reúne ${num(branch.notVisitedActive)} clientes ativos sem visita no recorte.`:'Nenhuma filial no recorte.',action:'Comparar o volume com a carteira da filial. O número isolado não mede desempenho do gestor.'}];
return {title:page,summary:'Leitura executiva do recorte selecionado',evolution:'Indicadores descritivos sobre dados fictícios. Não são previsões ou recomendações automáticas.',findings}}
export const DIRECTOR_PAGES=['Funil de Vendas','Visão Geral','Filiais','Vendedores','Trações','Qualidade do CRM','Ações Gerenciais','Mercado','Clientes (Emplacamentos)','Clientes (Carteira)','Território'];
