// Deterministic, entirely fictional demonstration. No production customer data.
export type Grid={title:string;headers:string[];rows:string[][]};
export type Filters={branches:string[];sellers:string[];periods:string[];ranges:{from:string;to:string}[];segment:string;traction:string;counting:string;adjust:boolean[];openMonth:boolean;status:string};
export const AS_OF='2026-09-18';
export const PERIODS=['Ano atual','Mês atual','Mês anterior','Últimos 90 dias','1º trimestre 2026','2º trimestre 2026','Ano anterior','Todo o histórico','Personalizado'];
export const BRANCHES=['Curitiba','Cascavel','Londrina','Ponta Grossa','Itajaí','Joinville'];
const FIRST=['Ana','Bruno','Carla','Diego','Elisa','Felipe','Gabriela','Henrique','Isabela','João','Laura','Marcos','Nádia','Otávio','Paula','Rafael','Sofia','Thiago','Valéria','William','Yasmin','Caio','Daniela','Eduardo'];
export const SELLERS=FIRST.map((s,i)=>({name:s+' '+['Andrade','Barros','Castro','Duarte'][i%4],branch:BRANCHES[Math.floor(i/4)]}));
export const TRACTIONS=['6x2','6x4','4x2','8x2','8x4','Outros'];
export type Client={id:number;group:number;name:string;branch:string;seller:string;city:string;segment:string;traction:string;crm:boolean;phone:boolean;email:boolean;contact:boolean;excluded:boolean;linked:boolean;created:string};
type Event={id:number;client:number;date:string;qty:number;brand:string;model:string;status:string;stage:string;age:number};
let seed=85436;const random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);const pick=<T,>(a:T[])=>a[Math.floor(random()*a.length)];
const date=(month:number)=>`${2025+Math.floor(month/12)}-${String(month%12+1).padStart(2,'0')}-${String(1+Math.floor(random()*(month===20?18:28))).padStart(2,'0')}`;
export const clients:Client[]=Array.from({length:864},(_,id)=>{const seller=SELLERS[id%24];return {id,group:Math.floor(id/2),name:`${['Horizonte','Via Norte','Rota Sul','Planalto','Vale Azul','Estrada Nova'][id%6]} ${['Transportes','Logística','Distribuição','Agrocargas'][Math.floor(id/6)%4]} ${String(Math.floor(id/2)+1).padStart(3,'0')}${id%2?' · Unidade 2':' · Matriz'}`,branch:seller.branch,seller:seller.name,city:seller.branch,segment:random()<.67?'Pesados':'Semipesados',traction:pick(['6x2','6x2','6x2','6x4','6x4','4x2','8x2','8x4','Outros']),crm:random()<.78,phone:random()<.91,email:random()<.77,contact:random()<.54,excluded:random()<.07,linked:random()<.95,created:date(Math.floor(random()*10))}});
// Municipal assignment is entirely fictional.
const demoMunicipalities:Record<string,string[]>={"Curitiba": ["Curitiba", "São José dos Pinhais", "Araucária", "Colombo"], "Cascavel": ["Cascavel", "Toledo", "Foz do Iguaçu", "Medianeira"], "Londrina": ["Londrina", "Cambé", "Arapongas", "Apucarana"], "Ponta Grossa": ["Ponta Grossa", "Castro", "Telêmaco Borba", "Irati"], "Itajaí": ["Itajaí", "Navegantes", "Balneário Camboriú", "Blumenau"], "Joinville": ["Joinville", "Jaraguá do Sul", "São Francisco do Sul", "Guaramirim"]};
for(const c of clients)c.city=demoMunicipalities[c.branch][Math.floor(c.id/24)%4];
const market:Event[]=[],visits:Event[]=[],opps:Event[]=[];
for(let month=0;month<=20;month++)for(const c of clients){if(c.created.slice(0,7)>`${2025+Math.floor(month/12)}-${String(month%12+1).padStart(2,'0')}`)continue;const bi=BRANCHES.indexOf(c.branch),si=SELLERS.findIndex(s=>s.name===c.seller);const season=1+.25*Math.sin(month*.75+bi);const partial=month===20?.6:1;const activity=(.14+(si%4)*.025)*season*partial;
 if(random()<activity){const brand=random()<.08+bi*.012+(month>=12?.018:0)?'DAF':pick(['VOLVO','SCANIA','MERCEDES-BENZ','VOLKSWAGEN','IVECO']);market.push({id:market.length,client:c.id,date:date(month),qty:1+Math.floor(random()*7),brand,model:brand==='DAF'?(c.segment==='Pesados'?'DAF XF':'DAF CF'):brand+'',status:'',stage:'',age:0});}
 if(c.crm&&random()<(.19+(si%4)*.07)*partial){for(let j=0;j<1+(random()<.2?1:0);j++)visits.push({id:visits.length,client:c.id,date:date(month),qty:1,brand:'',model:'',status:'',stage:'',age:0});}
 if(random()<.075*season*partial){const d=date(month),age=Math.floor((Date.parse(AS_OF)-Date.parse(d))/86400000);const r=random(),status=age<100&&r<.5?'Em aberto':r<.5?'Ganha':'Perdida';opps.push({id:opps.length,client:c.id,date:d,qty:1+Math.floor(random()*6),brand:'DAF',model:c.segment==='Pesados'?'DAF XF':'DAF CF',status,stage:pick(['Otimista','Otimista','Firme','Provável']),age});}}
export function range(period:string,custom:{from:string;to:string}){const map:Record<string,[string,string]>={'Ano atual':['2026-01-01',AS_OF],'Mês atual':['2026-09-01',AS_OF],'Mês anterior':['2026-08-01','2026-08-31'],'Últimos 90 dias':['2026-06-21',AS_OF],'1º trimestre 2026':['2026-01-01','2026-03-31'],'2º trimestre 2026':['2026-04-01','2026-06-30'],'Ano anterior':['2025-01-01','2025-12-31'],'Todo o histórico':['2025-01-01',AS_OF]};return period==='Personalizado'?[custom.from,custom.to]:map[period]||map['Ano atual'];}
export const num=(v:number)=>v.toLocaleString('pt-BR',{maximumFractionDigits:2});const percent=(a:number,b:number)=>b?a/b*100:0;const pct=(a:number,b:number)=>num(percent(a,b))+' %';const sum=(events:Event[])=>events.reduce((s,e)=>s+e.qty,0);const last=(events:Event[])=>events.map(e=>e.date).sort().at(-1)||'';const brdate=(d:string)=>d?d.split('-').reverse().join('/'):'—';
export function buildModel(f:Filters){
 const selected=clients.filter(c=>(!f.branches.length||f.branches.includes(c.branch))&&(!f.sellers.length||f.sellers.includes(c.seller))&&(f.segment==='Todos'||c.segment===f.segment)&&(f.traction==='Todos'||c.traction===f.traction));
 const marketIds=new Set(selected.filter(c=>(!f.adjust[0]||!['8x2','Outros'].includes(c.traction))&&(!f.adjust[1]||c.linked)&&(!f.adjust[2]||!c.excluded)).map(c=>c.id));
 const ids=new Set(selected.map(c=>c.id));const within=(e:Event,i:number)=>{const [a,b]=range(f.periods[i],f.ranges[i]);return ids.has(e.client)&&e.date>=a&&e.date<=b};
 const m=market.filter(e=>marketIds.has(e.client)&&within(e,0)),v=visits.filter(e=>within(e,1)),o=opps.filter(e=>within(e,2)&&(!f.openMonth||(e.status==='Em aberto'&&e.date>='2026-09-01'))&&(f.status==='Todos'||e.status===f.status));
 const groupKey=(id:number)=>f.counting.startsWith('Consolidar')?clients[id].group:id;
 const distinct=(events:Event[])=>new Set(events.map(e=>groupKey(e.client))).size;
 const count=(cs:Client[])=>new Set(cs.map(c=>groupKey(c.id))).size;
 const subset=(events:Event[],cs:Client[])=>{const set=new Set(cs.map(c=>c.id));return events.filter(e=>set.has(e.client));};
 const stats=(cs:Client[])=>{const mm=subset(m,cs),vv=subset(v,cs),oo=subset(o,cs),crm=cs.filter(c=>c.crm),vvCRM=vv.filter(e=>clients[e.client].crm);const active=new Set(mm.map(e=>groupKey(e.client))),visited=new Set(vvCRM.map(e=>groupKey(e.client))),open=new Set(oo.map(e=>groupKey(e.client)));const portfolio=count(crm),visitedN=visited.size;return {market:sum(mm),daf:sum(mm.filter(e=>e.brand==='DAF')),marketClients:distinct(mm),dafClients:distinct(mm.filter(e=>e.brand==='DAF')),visits:vv.length,visitedAll:distinct(vv),portfolio,active:count(crm.filter(c=>active.has(groupKey(c.id)))),visited:visitedN,unvisited:portfolio-visitedN,notVisitedActive:count(crm.filter(c=>active.has(groupKey(c.id))&&!visited.has(groupKey(c.id)))),visitedNoMarket:count(crm.filter(c=>visited.has(groupKey(c.id))&&!active.has(groupKey(c.id)))),outside:count(cs.filter(c=>!c.crm&&active.has(groupKey(c.id)))),noOpp:count(cs.filter(c=>active.has(groupKey(c.id))&&!open.has(groupKey(c.id)))),opp:oo.length,won:oo.filter(e=>e.status==='Ganha').length,lost:oo.filter(e=>e.status==='Perdida').length,open:oo.filter(e=>e.status==='Em aberto').length,trucks:sum(oo.filter(e=>e.status==='Em aberto')),oppClients:distinct(oo),phone:count(crm.filter(c=>c.phone)),email:count(crm.filter(c=>c.email)),contact:count(crm.filter(c=>c.contact)),lastVisit:last(vv),mm,vv,oo,crm};};
 const total=stats(selected),byBranch=BRANCHES.filter(b=>selected.some(c=>c.branch===b)).map(name=>({name,...stats(selected.filter(c=>c.branch===name))}));
 const bySeller=SELLERS.filter(s=>selected.some(c=>c.seller===s.name)).map(s=>({...s,...stats(selected.filter(c=>c.seller===s.name))}));
 const segs=['Pesados','Semipesados'].map(name=>({name,...stats(selected.filter(c=>c.segment===name))}));
 const g=(title:string,headers:string[],rows:(string|number)[][]):Grid=>({title,headers,rows:rows.map(r=>r.map(x=>typeof x==='number'?num(x):x))});
 const marketHeaders=['Emplacamentos','DAF','Share DAF %','Clientes Mercado','Clientes DAF','% Clientes DAF'];
 const marketRow=(s:typeof total)=>[s.market,s.daf,pct(s.daf,s.market),s.marketClients,s.dafClients,pct(s.dafClients,s.marketClients)];
 const coverageRow=(s:typeof total)=>[pct(s.visited,s.portfolio),s.visited,s.unvisited,s.notVisitedActive,s.visitedNoMarket];
 const coverageHeaders=['Cobertura %','Visitados Período','Não Visitados Período','Não Visitados Ativos','Visitados sem Emplacamento'];
 const sellerMarket=g('1. Mercado',['Filial','Vendedor',...marketHeaders],bySeller.map(s=>[s.branch,s.name,...marketRow(s)]));
 const branchTables=[g('1. Mercado',['Filial',...marketHeaders],byBranch.map(s=>[s.name,...marketRow(s)])),g('2. Atuação Comercial',['Filial','% Participação','Oportunidades Criadas','Visitas Realizadas','Visitas / Vendedor'],byBranch.map(s=>[s.name,pct(s.opp,total.opp),s.opp,s.visits,s.visits/Math.max(1,bySeller.filter(x=>x.branch===s.name).length)])),g('3. Carteira e Atividade',['Filial','Clientes Carteira','Clientes Ativos Período','% Carteira Ativo'],byBranch.map(s=>[s.name,s.portfolio,s.active,pct(s.active,s.portfolio)])),g('4. Cobertura',['Filial',...coverageHeaders],byBranch.map(s=>[s.name,...coverageRow(s)]))];
 const tractionTable=(segment:string)=>{const mm=m.filter(e=>clients[e.client].segment===segment);return g('Detalhamento por tração',['Tração','Emplacamentos','Composição no Segmento %','DAF','Share DAF %'],TRACTIONS.map(t=>{const es=mm.filter(e=>clients[e.client].traction===t),da=sum(es.filter(e=>e.brand==='DAF'));return [t,sum(es),pct(sum(es),sum(mm)),da,pct(da,sum(es))]}));};
 const groupClients=(cs:Client[])=>{const result=new Map<number,Client[]>();for(const c of cs){const k=groupKey(c.id);result.set(k,[...(result.get(k)||[]),c]);}return [...result.values()];};
 const grouped=groupClients(selected);const activeGroups=grouped.map(cs=>({cs,s:stats(cs)})).filter(x=>x.s.market>0).sort((a,b)=>b.s.market-a.s.market);
 const clientName=(cs:Client[])=>cs.length>1?cs[0].name.split(' · ')[0]+' · Grupo':cs[0].name;
 const clientRows=activeGroups.map(({cs,s})=>[clientName(cs),'CLI-'+String(cs[0].id+1).padStart(5,'0'),'GRUPO-'+String(cs[0].group+1).padStart(4,'0'),cs[0].city,cs.some(c=>c.crm)?cs[0].city:'Fora do CRM',s.market,sum(s.mm.filter(e=>clients[e.client].segment==='Pesados')),sum(s.mm.filter(e=>clients[e.client].segment==='Semipesados')),cs[0].branch,cs.map(c=>c.seller).filter((x,i,a)=>a.indexOf(x)===i).join(', '),s.daf,brdate(last(s.mm))]);
 const actionGroups=groupClients(selected.filter(c=>c.crm)).map(cs=>({cs,s:stats(cs)})).filter(x=>x.s.market>0&&x.s.visits===0).sort((a,b)=>b.s.market-a.s.market);
 const actionRows=actionGroups.map(({cs,s})=>[clientName(cs),'CLI-'+String(cs[0].id+1).padStart(5,'0'),cs[0].city,cs[0].branch,cs[0].seller,s.market,s.daf,s.visits,s.opp,brdate(last(s.mm)),brdate(s.lastVisit)]);
 const action=g('Indicadores por vendedor',['Filial','Nome do vendedor','Não Visitados Ativos','Clientes ativos Fora do CRM','Mercado sem Oportunidade','Visitados sem Emplacamento'],bySeller.map(s=>[s.branch,s.name,s.notVisitedActive,s.outside,s.noOpp,s.visitedNoMarket]));
 const pages:Record<string,Grid[]>={
 'Funil de Vendas':[g('Oportunidades do período',['Código','Vendedor','Cliente','Status','Funil','Motivo da Perda','Data Criação','Filial','Caminhões','Segmento','Tração','Modelo'],[...o].sort((a,b)=>b.date.localeCompare(a.date)).map(e=>{const c=clients[e.client];return ['OPP-'+(e.id+1000),c.seller,c.name,e.status,e.stage,e.status==='Perdida'?['Preço','Prazo','Concorrência'][e.id%3]:'—',brdate(e.date),c.branch,e.qty,c.segment,c.traction,e.model]}))],
 'Visão Geral':[g('Pesados x Semipesados',['Segmento','Emplacamentos','Clientes','DAF','Share DAF %'],segs.map(s=>[s.name,s.market,s.marketClients,s.daf,pct(s.daf,s.market)])),sellerMarket],
 'Filiais':branchTables,
 'Vendedores':[sellerMarket,g('Pesados x Semipesados',['Filial','Vendedor','Segmento','Emplacamentos','DAF','Share DAF %'],bySeller.flatMap(s=>['Pesados','Semipesados'].map(seg=>{const x=stats(selected.filter(c=>c.seller===s.name&&c.segment===seg));return [s.branch,s.name,seg,x.market,x.daf,pct(x.daf,x.market)]}))),g('2. Atuação Comercial',['Filial','Vendedor','% Participação','Oportunidades Criadas','Visitas Realizadas'],bySeller.map(s=>[s.branch,s.name,pct(s.opp,total.opp),s.opp,s.visits])),g('3. Carteira e Atividade',['Filial','Vendedor','Clientes Carteira','Clientes Ativos Período','% Carteira Ativo'],bySeller.map(s=>[s.branch,s.name,s.portfolio,s.active,pct(s.active,s.portfolio)])),g('4. Cobertura',['Filial','Vendedor',...coverageHeaders],bySeller.map(s=>[s.branch,s.name,...coverageRow(s)]))],
 'Trações':[tractionTable('Pesados')], 'Semipesados':[tractionTable('Semipesados'),g('Modelos mais emplacados',['Marca','Modelo','Segmento','Tração','Emplacamentos','Participação no Recorte %'],['DAF','VOLVO','SCANIA','MERCEDES-BENZ','VOLKSWAGEN','IVECO'].map(brand=>{const es=m.filter(e=>e.brand===brand&&clients[e.client].segment==='Semipesados');return [brand,brand==='DAF'?'DAF CF':brand+'','Semipesados','Todas',sum(es),pct(sum(es),segs[1].market)]}))],
 'Qualidade do CRM':[g('Resumo por vendedor',['Filial','Vendedor','Clientes','Com Tel.','Tel. %','Com E-mail','E-mail %','Com Contato Principal','Cont. Princ. %','Incompletos'],bySeller.map(s=>[s.branch,s.name,s.portfolio,s.phone,pct(s.phone,s.portfolio),s.email,pct(s.email,s.portfolio),s.contact,pct(s.contact,s.portfolio),count(s.crm.filter(c=>!c.phone||!c.email||!c.contact))]))],
 'Ações Gerenciais':[action],
 'Explorar Dados':[g('Marcas no período',['Marca','Emplacamentos','Share Mercado %'],['DAF','VOLVO','SCANIA','MERCEDES-BENZ','VOLKSWAGEN','IVECO'].map(brand=>({brand,q:sum(m.filter(e=>e.brand===brand))})).sort((a,b)=>b.q-a.q).map(x=>[x.brand,x.q,pct(x.q,total.market)]))],
 'Clientes (Emplacamentos)':[g('Clientes que emplacaram no período',['Cliente','Identificador','Grupo econômico','Cidade principal','Cidade CRM','Emplacamentos','Pesados','Semipesados','Filial','Responsável','DAF','Último emplacamento'],clientRows)],
 'Clientes (Carteira)':[g('Clientes da carteira',['Cliente','Identificador','Estabelecimentos vinculados','Responsável','Filial','Cidade CRM','Nível do perfil','Grupo econômico','Emplacamentos no período','Visitas no período','Oportunidades no período','Última visita','Telefone cadastrado','E-mail cadastrado','Contato principal'],groupClients(selected.filter(c=>c.crm)).map(cs=>{const s=stats(cs);return [clientName(cs),'CLI-'+String(cs[0].id+1).padStart(5,'0'),cs.length,cs.map(c=>c.seller).filter((x,i,a)=>a.indexOf(x)===i).join(', '),cs[0].branch,cs[0].city,cs.length>1?'Matriz / grupo':'Estabelecimento','Grupo econômico '+(cs[0].group+1),s.market,s.visits,s.opp,brdate(s.lastVisit),s.phone?'Sim':'Não',s.email?'Sim':'Não',s.contact?'Sim':'Não']}))],
 'Visitas':[g('Visitas por vendedor',['Filial','Vendedor','Visitas','Clientes Distintos','Visitas na Carteira Atual','Clientes Carteira','Visitados Período','Cobertura %','Última Visita'],bySeller.map(s=>[s.branch,s.name,s.visits,s.visitedAll,s.vv.filter(e=>clients[e.client].crm).length,s.portfolio,s.visited,pct(s.visited,s.portfolio),brdate(s.lastVisit)])),g('Histórico de visitas',['Data','Cliente','Vendedor','Filial','Segmento','Tração','Na carteira atual'],[...v].sort((a,b)=>b.date.localeCompare(a.date)).map(e=>{const c=clients[e.client];return [brdate(e.date),c.name,c.seller,c.branch,c.segment,c.traction,c.crm?'Sim':'Não']}))],
 'Lista de ação':[action,g('Não visitados ativos',['Cliente','Identificador','Cidade CRM','Filial Carteira','Responsável Carteira','Emplacamentos','DAF','Visitas Realizadas','Oportunidades Criadas','Último Emplacamento','Última Visita'],actionRows)]};
 const months=Array.from(new Set([...m,...v,...o].map(e=>e.date.slice(0,7)))).sort();
 const trend=months.map(month=>{const mm=m.filter(e=>e.date.startsWith(month)),vv=v.filter(e=>e.date.startsWith(month)),oo=o.filter(e=>e.date.startsWith(month));return {month,name:month.slice(5)+'/'+month.slice(2,4),market:sum(mm),daf:sum(mm.filter(e=>e.brand==='DAF')),share:percent(sum(mm.filter(e=>e.brand==='DAF')),sum(mm)),visits:vv.length,opps:oo.length,won:oo.filter(e=>e.status==='Ganha').length,clients:distinct(mm)};});
 return {filters:f,pages,total,byBranch,bySeller,segs,trend,selected,stages:['Otimista','Provável','Firme'].map(name=>({name,count:sum(o.filter(e=>e.status==='Em aberto'&&e.stage===name)),opps:o.filter(e=>e.status==='Em aberto'&&e.stage===name).length})),ages:[{name:'Até 30 dias',value:o.filter(e=>e.status==='Em aberto'&&e.age<=30).length},{name:'31–60 dias',value:o.filter(e=>e.status==='Em aberto'&&e.age>30&&e.age<=60).length},{name:'Mais de 60 dias',value:o.filter(e=>e.status==='Em aberto'&&e.age>60).length}],crmMarket:sum(m.filter(e=>clients[e.client].crm)),clientRows,actionRows,percent};
}
export type Model=ReturnType<typeof buildModel>;

export const BASE_METADATA={crm:clients.filter(c=>c.crm).length,establishments:clients.length,market:{from:market.map(e=>e.date).sort()[0],to:last(market)},visits:{from:visits.map(e=>e.date).sort()[0],to:last(visits)},opps:{from:opps.map(e=>e.date).sort()[0],to:last(opps)}};
