import {clients,num,type Model,type Client,type Grid} from './mock-data';
export type Metric='market'|'daf'|'marketClients'|'visited'|'portfolio'|'active'|'unvisited'|'notVisitedActive'|'outside'|'noOpp'|'visitedNoMarket'|'phoneMissing'|'emailMissing'|'contactMissing';
export const metricLabels:Record<Metric,string>={market:'Emplacamentos',daf:'Emplacamentos DAF',marketClients:'Clientes de mercado',visited:'Clientes visitados',portfolio:'Clientes da carteira',active:'Clientes ativos',unvisited:'Clientes sem visita',notVisitedActive:'Ativos sem visita',outside:'Ativos fora do CRM',noOpp:'Mercado sem oportunidade',visitedNoMarket:'Visitados sem emplacamento',phoneMissing:'Sem telefone',emailMissing:'Sem e-mail',contactMissing:'Sem contato principal'};
export const keyFor=(m:Model,c:Client)=>m.filters.counting.startsWith('Consolidar')?c.group:c.id;
export function metricGrid(m:Model,metric:Metric,scope?:{kind:'branch'|'seller';name:string}):{grid:Grid;value:number}{
 const selected=m.selected.filter(c=>!scope||(scope.kind==='branch'?c.branch===scope.name:c.seller===scope.name)),ids=new Set(selected.map(c=>c.id));
 const mm=m.total.mm.filter(e=>ids.has(e.client)),vv=m.total.vv.filter(e=>ids.has(e.client)),oo=m.total.oo.filter(e=>ids.has(e.client));
 const keys=(a:{client:number}[])=>new Set(a.map(e=>keyFor(m,clients[e.client]))),active=keys(mm),visited=keys(vv.filter(e=>clients[e.client].crm)),opp=keys(oo);
 const grouped=new Map<number,Client[]>();for(const c of selected){const k=keyFor(m,c);grouped.set(k,[...(grouped.get(k)||[]),c])}
 const amounts=new Map<number,{market:number;daf:number;visits:number;opps:number}>();for(const key of grouped.keys())amounts.set(key,{market:0,daf:0,visits:0,opps:0});for(const e of mm){const a=amounts.get(keyFor(m,clients[e.client]))!;a.market+=e.qty;if(e.brand==='DAF')a.daf+=e.qty}for(const e of vv)amounts.get(keyFor(m,clients[e.client]))!.visits++;for(const e of oo)amounts.get(keyFor(m,clients[e.client]))!.opps++;
 const rows:string[][]=[];let value=0;
 for(const [key,cs] of grouped){const crm=cs.filter(c=>c.crm);const matches=metric==='market'||metric==='marketClients'?active.has(key):metric==='daf'?amounts.get(key)!.daf>0:metric==='visited'?visited.has(key):metric==='portfolio'?crm.length>0:metric==='active'?crm.length>0&&active.has(key):metric==='unvisited'?crm.length>0&&!visited.has(key):metric==='notVisitedActive'?crm.length>0&&active.has(key)&&!visited.has(key):metric==='outside'?cs.some(c=>!c.crm)&&active.has(key):metric==='noOpp'?active.has(key)&&!opp.has(key):metric==='visitedNoMarket'?crm.length>0&&visited.has(key)&&!active.has(key):metric==='phoneMissing'?crm.length>0&&!crm.some(c=>c.phone):metric==='emailMissing'?crm.length>0&&!crm.some(c=>c.email):crm.length>0&&!crm.some(c=>c.contact);
 if(!matches)continue;const {market,daf,visits,opps}=amounts.get(key)!;value+=metric==='market'?market:metric==='daf'?daf:1;const c=cs[0];rows.push([cs.length>1?c.name.split(' · ')[0]+' · Grupo':c.name,'CLI-'+String(c.id+1).padStart(5,'0'),[...new Set(cs.map(c=>c.branch))].join(', '),[...new Set(cs.map(c=>c.seller))].join(', '),[...new Set(cs.map(c=>c.city))].join(', '),num(market),num(daf),num(visits),num(opps),crm.some(c=>c.phone)?'Sim':'Não',crm.some(c=>c.email)?'Sim':'Não',crm.some(c=>c.contact)?'Sim':'Não']);}
 return {value,grid:{title:metricLabels[metric]+(scope?' · '+scope.name:''),headers:['Cliente','Identificador','Filiais','Responsáveis','Municípios','Emplacamentos','DAF','Visitas','Oportunidades','Telefone','E-mail','Contato principal'],rows}};
}
export const visitDescription=(id:number)=>['Visita de acompanhamento da operação. Cliente relatou necessidade de avaliar renovação da frota; responsável combinou levantar configurações e prazo de entrega.','Reunião sobre a utilização atual dos veículos. Registradas dúvidas de manutenção e disponibilidade. Próximo contato previsto após validação interna do cliente.','Apresentação de configuração para transporte regional. Cliente solicitou comparativo de condições e capacidade de carga antes de avançar.','Contato presencial para atualização cadastral e entendimento das rotas. Sem previsão de compra confirmada nesta visita.'][id%4];
