import {num,range,type Model,type Grid} from './mock-data';
import {metricGrid,visitDescription,type Metric} from './operational-data';
import {territoryRows} from './territory-data';
import {directorInsight,DIRECTOR_PAGES,type DemoRole} from './director-data';
export type ReportChart={title:string;data:{name:string;value:number}[];note?:string};
const n=(v:string)=>Number(v.replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''));
export function reportCharts(m:Model):ReportChart[]{const top=m.clientRows.slice(0,10).reduce((s,r)=>s+Number(r[5]),0);return [
{title:'Funil • caminhões por estágio',data:m.stages.map(s=>({name:s.name,value:s.count}))},
{title:'Filiais • participação DAF (%)',data:m.byBranch.map(s=>({name:s.name,value:m.percent(s.daf,s.market)}))},
{title:'Filiais • clientes visitados',data:m.byBranch.map(s=>({name:s.name,value:s.visited}))},
{title:'Vendedores • participação DAF (%)',data:m.bySeller.map(s=>({name:s.name,value:m.percent(s.daf,s.market)}))},
...['Trações','Semipesados'].flatMap(k=>[{title:k+' • composição de mercado',data:m.pages[k][0].rows.map(r=>({name:r[0],value:n(r[1])}))},{title:k+' • participação DAF (%)',data:m.pages[k][0].rows.map(r=>({name:r[0],value:n(r[4])}))}]),
{title:'CRM • preenchimento (%)',data:[{name:'Telefone',value:m.percent(m.total.phone,m.total.portfolio)},{name:'E-mail',value:m.percent(m.total.email,m.total.portfolio)},{name:'Contato principal',value:m.percent(m.total.contact,m.total.portfolio)}]},
{title:'Mercado • participação por marca (%)',data:m.pages['Explorar Dados'][0].rows.map(r=>({name:r[0],value:n(r[2])}))},
{title:'Clientes • concentração do volume de compras',data:[{name:'Dez maiores',value:top},{name:'Demais clientes',value:m.total.market-top}]},
{title:'Carteira • clientes por filial',data:m.byBranch.map(s=>({name:s.name,value:s.portfolio}))}]}
export function reportTables(m:Model):{page:string;grid:Grid}[]{const out=Object.entries(m.pages).filter(([p])=>!['Visitas','Lista de ação'].includes(p)).flatMap(([page,tables])=>tables.map(grid=>({page:page==='Explorar Dados'?'Mercado':page,grid})));for(const key of ['phoneMissing','emailMissing','contactMissing','notVisitedActive','outside','noOpp','visitedNoMarket'] as Metric[])out.push({page:key.endsWith('Missing')?'Qualidade do CRM':'Ações Gerenciais',grid:metricGrid(m,key).grid});out.push({page:'Carteira de clientes',grid:{title:'Histórico de visitas por cliente',headers:[...m.pages.Visitas[1].headers,'Descrição fictícia'],rows:[...m.total.vv].sort((a,b)=>b.date.localeCompare(a.date)).map((e,i)=>[...m.pages.Visitas[1].rows[i],visitDescription(e.id)])}});out.push({page:'Território',grid:{title:'Indicadores por município',headers:['Município','Emplacamentos','Visitas','Estabelecimentos na carteira','Ativos sem visita'],rows:territoryRows(m).map(r=>[r.name,num(r.market),num(r.visits),num(r.portfolio),num(r.uncovered)])}});return out}
export function filterDescription(m:Model){const f=m.filters;return ['Filiais: '+(f.branches.join(', ')||'Todas'),'Vendedores: '+(f.sellers.join(', ')||'Todos'),'Segmento: '+f.segment+'; tração: '+f.traction,'Contagem: '+f.counting,...['Emplacamentos','Visitas','Oportunidades'].map((name,i)=>name+': '+range(f.periods[i],f.ranges[i]).join(' a ')),'Exclusões de mercado: '+(['Sem produto DAF','Sem vínculo de filial','Exclusões gerenciais'].filter((_,i)=>f.adjust[i]).join(', ')||'Nenhuma'),'Status de oportunidades: '+f.status+'; abertas no mês: '+(f.openMonth?'Sim':'Não')];}
export function reportInsights(m:Model,role:DemoRole='manager'){return role==='director'?DIRECTOR_PAGES.map(p=>directorInsight(p,m)):[]}
export const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function chartSvg(c:ReportChart){const max=Math.max(1,...c.data.map(d=>d.value));const h=Math.max(110,c.data.length*30+25);return `<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="${h}" viewBox="0 0 1000 ${h}"><rect width="1000" height="${h}" fill="white"/>${c.data.length?c.data.map((d,i)=>`<text x="8" y="${i*30+23}" font-family="Arial" font-size="13" fill="#36546c">${esc(d.name.slice(0,38))}</text><rect x="300" y="${i*30+8}" width="${d.value/max*580}" height="19" rx="3" fill="#087db9"/><text x="${310+d.value/max*580}" y="${i*30+23}" font-family="Arial" font-size="13" fill="#214967">${num(d.value)}</text>`).join(''):'<text x="20" y="45" font-family="Arial" font-size="16">Sem dados no recorte</text>'}</svg>`;}
